version: '3'

services:
  pq_database:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      - service_network

  service:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - pq_database
    networks:
      - service_network
    ports:
      - "${PORT}:${PORT}"
    environment:
      - DSN=${DSN}
      - API_URL=${API_URL}
      - PORT=${PORT}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}

networks:
  service_network:
    driver: bridge
