version: '3'

services:
  pq_database:
    image: postgres:latest
    restart: always
    environment:
      MYSQL_DATABASE: Efficent
      MYSQL_USER: Efficent
      MYSQL_PASSWORD: efficent
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    networks:
      - service_network

  service:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - pq_database
    networks:
      - service_network
    ports:
      - "8080:8080"
    environment:
      PORT: '8080'

networks:
  service_network:
    driver: bridge